version: '3.0'
services:
# The database
  mongoDb:
    image: mongo:latest
    container_name: mongo-service
    restart: always
    command: [ --auth ]
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

# Mongo Express to visualize db on browser
  mongo-express:
    image: mongo-express
    container_name: mongo-workbench
    depends_on:
      - mongoDb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongoDb:27017/

# The application and API
  bankApi:
    build: '.'
    container_name: we-grow-bank-service
    restart: always
    env_file:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - mongoDb
    volumes:
      - './:/app'
      - '/app/node_modules'

volumes:
  mongodb_data_container:
